clear; close all; clc;

num_tracker = 68;
results = [
    struct('tracker','QuadFC','eao',0.343),...
    struct('tracker','SiamRPN','eao',0.341),...
    struct('tracker','CCOT','eao',0.331),...
    struct('tracker','TCNN','eao',0.325),...
    struct('tracker','VITAL','eao',0.323),...
    struct('tracker','ECO-HC','eao',0.323),...
    struct('tracker','SSAT','eao',0.321),...
    struct('tracker','MLDF','eao',0.311),...
    struct('tracker','TADT','eao',0.299),...
    struct('tracker','Staple','eao',0.295),...
    struct('tracker','DDC','eao',0.293),...
    struct('tracker','SA-Siam','eao',0.291),...
    struct('tracker','EBT','eao',0.291),...
    struct('tracker','SRBT','eao',0.290),...
    struct('tracker','STAPLEp','eao',0.286),...
    struct('tracker','DNT','eao',0.278),...
    struct('tracker','SSKCF','eao',0.277),...
    struct('tracker','SiamFC-R','eao',0.277),...
    struct('tracker','DeepSRDCF','eao',0.276),...
    struct('tracker','SHCT','eao',0.266),...
    struct('tracker','MDNet','eao',0.257),...
    struct('tracker','FCF','eao',0.251),...
    struct('tracker','SRDCF','eao',0.247),...
    struct('tracker','RFD_CF2','eao',0.241),...
    struct('tracker','GGTv2','eao',0.238),...
    struct('tracker','SiamFC-A','eao',0.235),...
    struct('tracker','deepMKCF','eao',0.232),...
    struct('tracker','NSAMF','eao',0.227),...
    struct('tracker','ColorKCF','eao',0.226),...
    struct('tracker','CCCT','eao',0.223),...
    struct('tracker','SO-DLT','eao',0.221),...
    struct('tracker','HCF','eao',0.220),...
    struct('tracker','GCF','eao',0.218),...
    struct('tracker','SMACF','eao',0.218),...
    struct('tracker','DAT','eao',0.217),...
    struct('tracker','ASMS','eao',0.212),...
    struct('tracker','ANT','eao',0.204),...
    struct('tracker','MAD','eao',0.202),...
    struct('tracker','BST','eao',0.20),...
    struct('tracker','KCF2014','eao',0.192),...
    struct('tracker','OEST','eao',0.188),...
    struct('tracker','SCT','eao',0.188),...
    struct('tracker','SAMF2014','eao',0.186),...
    struct('tracker','SWCF','eao',0.185),...
    struct('tracker','DSST2014','eao',0.181),...
    struct('tracker','TGPR','eao',0.181),...
    struct('tracker','DPCF','eao',0.179),...
    struct('tracker','ACT','eao',0.173),...
    struct('tracker','LGT','eao',0.168),...
    struct('tracker','ART_DSST','eao',0.167),...
    struct('tracker','MLT','eao',0.165),...
    struct('tracker','CDTT','eao',0.164),...
    struct('tracker','sKCF','eao',0.153),...
    struct('tracker','DFST','eao',0.151),...
    struct('tracker','HT','eao',0.15),...
    struct('tracker','SMPR','eao',0.147),...
    struct('tracker','FoT','eao',0.142),...
    struct('tracker','STRUCK','eao',0.142),...
    struct('tracker','FCT','eao',0.141),...
    struct('tracker','DFT','eao',0.139),...
    struct('tracker','BDF','eao',0.136),...
    struct('tracker','LT_FLO','eao',0.126),...
    struct('tracker','IVT','eao',0.115),...
    struct('tracker','STC','eao',0.11),...
    struct('tracker','FT','eao',0.104),...
    struct('tracker','CTF','eao',0.092),...
    struct('tracker','CMT','eao',0.083),...
    struct('tracker','NCC','eao',0.08),...
    ];

...........
figure;
Maker_style = {'o','x','*','v','diamond','+','<','pentagram','>','square','^','hexagram'};
Color_style = hsv(7);
line([0,num_tracker+1],[0.255,0.255],'LineWidth',2,'Color',[0.7 0.7 0.7]); hold on;
recent_index = [1,2,4,5,7,10,13,15,17,22,28,31,36,39,50];

for i = 1:num_tracker
    if i == 1 || i == 3
        m(i) = plot(i,results(i).eao,'Marker','.','Color',Color_style(i,:),...
            'LineStyle','none','LineWidth',2,'MarkerSize',35);hold on;
    else
        m(i) = plot(i,results(i).eao,'Marker',Maker_style{mod(i-1,12)+1},'Color',Color_style(mod(i-1,7)+1,:),...
            'LineStyle','none','LineWidth',2,'MarkerSize',10);hold on;
    end
    plot([i,i],[0,results(i).eao],'LineStyle',':','Color',[0.83 0.81 0.78]);hold on;
    if any(i == recent_index)
        plot(i+2, 0.075,'MarkerSize',6,'Marker','o','LineStyle','none',...
            'Color',[0.83 0.81 0.8],'LineWidth',2);hold on;
    end
end

set(gca,'xdir','reverse')
ylim([0.05,0.37]);
%ylim([0,(eao_sorted(1)+0.05)]);
xlim([1, num_tracker+1]);
set(gca,'XTick',1:5:70);
set(gca,'YTick',0:0.05:(0.4))
set(gca,'linewidth',2);
set(gca,'FontSize',12);
title('EAO Scores Rank on VOT2016', 'FontName','Times New Roman','FontSize',14)
%annotation('textarrow',[0.76,0.8],[0.76,0.72],'String','SAECO','FontWeight','bold','FontSize',12);
annotation('textbox',[.15,.78,.1,.1],'String','$$\hat{\Phi}$$','FontWeight','bold','FontSize',30,'LineStyle','none','Interpreter','latex','FitBoxToText','off')
box on

num_tracker_show = 12; % only write top10
% for i = 1:num_tracker_show %
%     legend_names{i} = [strrep(tracker_names{i},'_','\_'),...
%         num2str(eao_sorted(i),'~[%0.3f]')];
% end
% legend(m(1:num_tracker_show),legend_names(1:num_tracker_show),...
%     'Location','eastoutside','Interpreter', 'latex','FontSize',16)

legend(m(1:num_tracker_show),{'\textbf{QuadFC [0.343]}', 'SiamRPN [0.341]', 'CCOT [0.331]', 'TCNN [0.325]', 'VITAL [0.323]', 'ECO-HC [0.323]',...
    'SSAT [0.321]', 'MLDF [0.311]', 'TADT [0.299]', 'Staple [0.295]', 'DDC [0.293]', 'SA-Siam [0.291]'},...
    'Location','eastoutside','Interpreter', 'latex','FontSize',12)
    
set(gcf, 'position', [500 300 800 250]);
saveas(gcf,'../img/eao_vot2016','pdf');
saveas(gcf,'../img/eao_vot2016','png');

