clear; close all; clc;

num_tracker = 53;
results = [
    struct('tracker','LSART','eao',0.323),...
    struct('tracker','CSART','eao',0.318),...
    struct('tracker','CFWCF','eao',0.303),...
    struct('tracker','CFCF','eao',0.286),...
    struct('tracker','ECO','eao',0.280),...
    struct('tracker','Gnet','eao',0.274),...
    struct('tracker','MCCT','eao',0.27),...
    struct('tracker','CCOT','eao',0.267),...
    struct('tracker','CSRDCF','eao',0.256),...
    struct('tracker','SiamDCF','eao',0.249),...
    struct('tracker','MCPF','eao',0.248),...
    struct('tracker','SiamRPN','eao',0.244),...
    struct('tracker','CRT','eao',0.244),...
    struct('tracker','ECO-HC','eao',0.238),...
    struct('tracker','DLST','eao',0.233),...
    struct('tracker','CSRDCF++','eao',0.229),...
    struct('tracker','CSRDCFf','eao',0.227),...
    struct('tracker','RCPF','eao',0.215),...
    struct('tracker','UCT','eao',0.206),...
    struct('tracker','SPCT','eao',0.204),...
    struct('tracker','ATLAS','eao',0.195),...
    struct('tracker','MEEM','eao',0.192),...
    struct('tracker','FSTC','eao',0.188),...
    struct('tracker','SiamFC','eao',0.188),...
    struct('tracker','SAPKLTF','eao',0.184),...
    struct('tracker','Staple','eao',0.169),...
    struct('tracker','ASMS','eao',0.169),...
    struct('tracker','ANT','eao',0.168),...
    struct('tracker','KFebT','eao',0.168),...
    struct('tracker','HMMTxD','eao',0.168),...
    struct('tracker','MSSA','eao',0.167),...
    struct('tracker','SSKCF','eao',0.166),...
    struct('tracker','DPT','eao',0.158),...
    struct('tracker','GMDnetN','eao',0.157),...
    struct('tracker','LGT','eao',0.144),...
    struct('tracker','MOSSEca','eao',0.141),...
    struct('tracker','CGS','eao',0.14),...
    struct('tracker','KCF','eao',0.135),...
    struct('tracker','GMD','eao',0.13),...
    struct('tracker','FoT','eao',0.13),...
    struct('tracker','CHT','eao',0.122),...
    struct('tracker','SRDCF','eao',0.119),...
    struct('tracker','MLT','eao',0.118),...
    struct('tracker','BST','eao',0.115),...
    struct('tracker','DPRF','eao',0.114),...
    struct('tracker','LDES','eao',0.111),...
    struct('tracker','CMT','eao',0.098),...
    struct('tracker','Struck2011','eao',0.097),...
    struct('tracker','DSST','eao',0.079),...
    struct('tracker','LTFLO','eao',0.078),...
    struct('tracker','IVT','eao',0.076),...
    struct('tracker','L1APG','eao',0.069),...
    struct('tracker','FragTrack','eao',0.068),...
    ];

...........
figure;
Maker_style = {'o','x','*','v','diamond','+','<','pentagram','>','square','^','hexagram'};
Color_style = hsv(7);
line([0,num_tracker+1],[0.202,0.202],'LineWidth',2,'Color',[0.7 0.7 0.7]); hold on;
recent_index = [1,2,4,5,7,10,13,15,17,22,28,31,36,39,50];

for i = 1:num_tracker
    if i == 1 || i == 3
        m(i) = plot(i,results(i).eao,'Marker','.','Color',Color_style(i,:),...
            'LineStyle','none','LineWidth',2,'MarkerSize',35);hold on;
    else
        m(i) = plot(i,results(i).eao,'Marker',Maker_style{mod(i-1,12)+1},'Color',Color_style(mod(i-1,7)+1,:),...
            'LineStyle','none','LineWidth',2,'MarkerSize',10);hold on;
    end
    plot([i,i],[0,results(i).eao],'LineStyle',':','Color',[0.83 0.81 0.78]);hold on;
    if any(i == recent_index)
        plot(i+2, 0.05,'MarkerSize',6,'Marker','o','LineStyle','none',...
            'Color',[0.83 0.81 0.8],'LineWidth',2);hold on;
    end
end

set(gca,'xdir','reverse')
ylim([0,0.37]);
%ylim([0,(eao_sorted(1)+0.05)]);
xlim([1, num_tracker+1]);
set(gca,'XTick',1:5:70);
set(gca,'YTick',0:0.05:(0.37))
set(gca,'linewidth',2);
set(gca,'FontSize',12);
title('EAO Scores Rank on VOT2017', 'FontName','Times New Roman','FontSize',14)
annotation('textarrow',[0.7,0.78],[0.66,0.74],'String','SAECO','FontWeight','bold','FontSize',12);
annotation('textbox',[.15,.8,.1,.1],'String','$$\hat{\Phi}$$','FontWeight','bold','FontSize',30,'LineStyle','none','Interpreter','latex','FitBoxToText','off')
box on

num_tracker_show = 12; % only write top10
% for i = 1:num_tracker_show %
%     legend_names{i} = [strrep(tracker_names{i},'_','\_'),...
%         num2str(eao_sorted(i),'~[%0.3f]')];
% end
% legend(m(1:num_tracker_show),legend_names(1:num_tracker_show),...
%     'Location','eastoutside','Interpreter', 'latex','FontSize',16)

legend(m(1:num_tracker_show),{'LSART [0.323]', '\textbf{CSART [0.318]}', 'CFWCR [0.303]', 'CFCF [0.286]', 'ECO [0.28]', 'Gnet [0.274]', 'MCCT [0.27]',...
    'CCOT [0.267]', 'CSRDCF [0.256]', 'SiamDCF [0.249]', 'MCPF [0.248]', 'SiamRPN [0.244]'},...
    'Location','eastoutside','Interpreter', 'latex','FontSize',12.5)
    
set(gcf, 'position', [500 300 800 250]);
saveas(gcf,'../img/eao_vot2017','pdf');
saveas(gcf,'../img/eao_vot2017','png');
