clear; close all; clc;

num_tracker = 65;
results = [
    struct('tracker','DiMP-50','eao',0.44),...
    struct('tracker','SiamRPN++','eao',0.414),...
    struct('tracker','ATOM','eao',0.401),...
    struct('tracker','LADCF','eao',0.389),...
    struct('tracker','MFT','eao',0.385),...
    struct('tracker','DaSiamRPN','eao',0.383),...
    struct('tracker','UPDT','eao',0.378),...
    struct('tracker','RCO','eao',0.376),...
    struct('tracker','DRT','eao',0.356),...
    struct('tracker','DeepSTRCF','eao',0.345),...
    struct('tracker','CPT','eao',0.339),...
    struct('tracker','SA_Siam_R','eao',0.337),...
    struct('tracker','DLSTpp','eao',0.325),...
    struct('tracker','LSART','eao',0.323),...
    struct('tracker','SRCT','eao',0.31),...
    struct('tracker','CFTR','eao',0.3),...
    struct('tracker','CPT_fast','eao',0.296),...
    struct('tracker','DeepCSRDCF','eao',0.293),...
    struct('tracker','SiamVGG','eao',0.286),...
    struct('tracker','SA_Siam_P','eao',0.286),...
    struct('tracker','CFCF','eao',0.282),...
    struct('tracker','ECO','eao',0.28),...
    struct('tracker','MCCT','eao',0.274),...
    struct('tracker','CCOT','eao',0.267),...
    struct('tracker','csrtpp','eao',0.263),...
    struct('tracker','LWDCT','eao',0.261),...
    struct('tracker','R_MCPF','eao',0.257),...
    struct('tracker','FSAN','eao',0.256),...
    struct('tracker','CSRDCF','eao',0.256),...
    struct('tracker','DCFCF','eao',0.249),...
    struct('tracker','UpdateNet','eao',0.244),...
    struct('tracker','MBSiam','eao',0.241),...
    struct('tracker','ALAL','eao',0.232),...
    struct('tracker','CSTEM','eao',0.226),...
    struct('tracker','C3DT','eao',0.209),...
    struct('tracker','RSECF','eao',0.206),...
    struct('tracker','DSiam','eao',0.196),...
    struct('tracker','MEEM','eao',0.192),...
    struct('tracker','SiamFC','eao',0.188),...
    struct('tracker','STST','eao',0.187),...
    struct('tracker','DCFNet','eao',0.182),...
    struct('tracker','DensSiam','eao',0.174),...
    struct('tracker','SAPKLTF','eao',0.171),...
    struct('tracker','Staple','eao',0.169),...
    struct('tracker','ASMS','eao',0.169),...
    struct('tracker','ANT','eao',0.168),...
    struct('tracker','DPT','eao',0.158),...
    struct('tracker','STBACF','eao',0.155),...
    struct('tracker','PBTS','eao',0.152),...
    struct('tracker','DAT','eao',0.144),...
    struct('tracker','RANet','eao',0.141),...
    struct('tracker','TRACA','eao',0.137),...
    struct('tracker','KCF','eao',0.135),...
    struct('tracker','FoT','eao',0.13),...
    struct('tracker','srdcf_dif','eao',0.126),...
    struct('tracker','SRDCF','eao',0.119),...
    struct('tracker','MLT','eao',0.118),...
    struct('tracker','BST','eao',0.116),...
    struct('tracker','Struck','eao',0.097),...
    struct('tracker','BDF','eao',0.093),...
    struct('tracker','MRSNCC','eao',0.082),...
    struct('tracker','DSST','eao',0.079),...
    struct('tracker','IVT','eao',0.076),...
    struct('tracker','CPOINT','eao',0.070),...
    struct('tracker','FragTrack','eao',0.068),...
    ];

...........
figure;
Maker_style = {'o','x','*','v','diamond','+','<','pentagram','>','square','^','hexagram'};
Color_style = hsv(7);
line([0,num_tracker+1],[0.28,0.28],'LineWidth',2,'Color',[0.7 0.7 0.7]); hold on;
recent_index = [1,2,4,5,7,10,13,15,17,22,28,31,36,39,50];

for i = 1:num_tracker
    if i == 1 || i == 3
        m(i) = plot(i,results(i).eao,'Marker','.','Color',Color_style(i,:),...
            'LineStyle','none','LineWidth',2,'MarkerSize',35);hold on;
    else
        m(i) = plot(i,results(i).eao,'Marker',Maker_style{mod(i-1,12)+1},'Color',Color_style(mod(i-1,7)+1,:),...
            'LineStyle','none','LineWidth',2,'MarkerSize',10);hold on;
    end
    plot([i,i],[0,results(i).eao],'LineStyle',':','Color',[0.83 0.81 0.78]);hold on;
    if any(i == recent_index)
        plot(i+2, 0.05,'MarkerSize',6,'Marker','o','LineStyle','none',...
            'Color',[0.83 0.81 0.8],'LineWidth',2);hold on;
    end
end

set(gca,'xdir','reverse')
ylim([0,0.46]);
%ylim([0,(eao_sorted(1)+0.05)]);
xlim([1, num_tracker+1]);
set(gca,'XTick',1:5:70);
set(gca,'YTick',0:0.05:(0.46))
set(gca,'linewidth',2);
set(gca,'FontSize',12);
title('EAO Scores Rank on VOT2018', 'FontName','Times New Roman','FontSize',14)
%annotation('textarrow',[0.7,0.78],[0.66,0.74],'String','SAECO','FontWeight','bold','FontSize',12);
annotation('textbox',[.15,.8,.1,.1],'String','$$\hat{\Phi}$$','FontWeight','bold','FontSize',30,'LineStyle','none','Interpreter','latex','FitBoxToText','off')
box on

num_tracker_show = 12; % only write top10
% for i = 1:num_tracker_show %
%     legend_names{i} = [strrep(tracker_names{i},'_','\_'),...
%         num2str(eao_sorted(i),'~[%0.3f]')];
% end
% legend(m(1:num_tracker_show),legend_names(1:num_tracker_show),...
%     'Location','eastoutside','Interpreter', 'latex','FontSize',16)

legend(m(1:num_tracker_show),{'DiMP-50 [0.440]', 'SiamRPN++ [0.414]', 'ATOM [0.401]', 'LADCF [0.389]', 'MFT [0.389]', 'DaSiamRPN [0.383]', 'UPDT [0.378]',...
    'RCO [0.376]', 'DRT [0.356]', 'DeepSTRCF [0.345]', 'CPT [0.339]', 'SA-Siam-R [0.337]'},...
    'Location','eastoutside','Interpreter', 'latex','FontSize',12.5)
    
set(gcf, 'position', [500 300 800 250]);
saveas(gcf,'../img/eao_vot2018','pdf');
saveas(gcf,'../img/eao_vot2018','png');
